### ISSUE TITLE
a little request

### ISSUE THREAD

**Issue by drakulaboy** [Henry-ZHR/telegram_font#1]
Hi, can you make it for Twitter too, please. The fonts in twitter are in res/font folder

**Comment by Henry-ZHR** [comment]
Seems that hooking [Resources.getFont](https://developer.android.com/reference/android/content/res/Resources.html#getFont(int)) is enough

You can write it yourself :)

**Comment by drakulaboy** [comment]
i'm kinda bad at kotlin coding [😳](https://emojipedia.org/flushed-face/) , help please just this time [😳](https://emojipedia.org/flushed-face/)

**Comment by Henry-ZHR** [comment]
You can also use Java

Simply read the documentation of Xposed API first

---

Sorry but I don't have enough time recently

**Comment by drakulaboy** [comment]
ok, thank you, with your modules i've learned a lot, and i made some little modules too
